name: Environment Secret Proof of Concept

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Provide a text input to process."
        required: true
        type: string

jobs:
  first_job:
    name: Input processing
    runs-on: ubuntu-slim
    outputs:
      consumed_input: ${{ steps.process_output.outputs.result }}
      
    steps:
      - name: Print input
        run: |
          echo "The workflow_dispatch text input was: ${{ github.event.inputs.message }}"

      - name: Generate output
        id: process_output
        run: | 
          echo "result=${{ github.event.inputs.message }}" >> $GITHUB_OUTPUT
    
